
-- This file has been automatically generated by SimUAid.

library ieee;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;

library SimUAid_synthesis;
--use SimUAid_synthesis.SimuAid_synthesis_pack.all;

entity lab3noseg is
port(A, B, C, D: in STD_LOGIC;

	S1, S2, S3, S4, S5, S6, S7, AN3, AN2, AN1, 
	AN0: out STD_LOGIC
	);
end lab3noseg;

architecture Structure of lab3noseg is
	signal Vnet_0, Vnet_1, Vnet_2, Ap, Vnet_3, Bp, Vnet_4, Cp, Dp, Vnet_5, 
		Vnet_6, Vnet_7, Vnet_8, Vnet_9, Vnet_10, Vnet_11, Vnet_12, Vnet_13, Vnet_14, Vnet_15, 
		Vnet_16, Vnet_17, Vnet_18, Vnet_19, Vnet_20, Vnet_21: STD_LOGIC;
	 component inverter
               port (
                       A: in STD_LOGIC;
                       B: out STD_LOGIC
               );
               end component;
      component nand2
               port (
                        A: in STD_LOGIC;
                        B: in STD_LOGIC;
                        C: out STD_LOGIC
               );
               end component;
      component nand3
               port (
                        A: in STD_LOGIC;
                        B: in STD_LOGIC;
                        C: in STD_LOGIC;
                        D: out STD_LOGIC
               );
               end component;
       component nand4
               port (
                        A: in STD_LOGIC;
                        B: in STD_LOGIC;
                        C: in STD_LOGIC;
                        D: in STD_LOGIC;
                        E: out STD_LOGIC
               );
               end component;               
	
begin
	VHDL_Device_0: inverter port map (A, Ap);
	VHDL_Device_1: inverter port map (B, Bp);
	VHDL_Device_2: inverter port map (C, Cp);
	VHDL_Device_3: inverter port map (D, Dp);
	VHDL_Device_4: nand2 port map (Dp, C, Vnet_0);
	VHDL_Device_5: nand2 port map (D, Cp, Vnet_1);
	X1: nand4 port map (Ap, B, Vnet_0, Vnet_1, Vnet_2);
	X2: nand2 port map (Bp, Cp, Vnet_3);
	X3: nand3 port map (Ap, Cp, D, Vnet_4);
	VHDL_Device_6: nand2 port map (Bp, D, Vnet_5);
	VHDL_Device_7: nand2 port map (A, Cp, Vnet_7);
	X4: nand4 port map (Vnet_1, Vnet_5, Vnet_6, Vnet_7, Vnet_8);
	VHDL_Device_8: nand3 port map (B, C, Dp, Vnet_6);
	X5: nand2 port map (Vnet_1, Vnet_5, Vnet_9);
	VHDL_Device_9: nand2 port map (C, D, Vnet_10);
	X6: nand2 port map (Vnet_7, Vnet_10, Vnet_11);
	VHDL_Device_10: nand2 port map (B, D, Vnet_12);
	VHDL_Device_11: nand2 port map (A, D, Vnet_13);
	VHDL_Device_12: nand3 port map (Ap, B, C, Vnet_14);
	X7: nand4 port map (Vnet_7, Vnet_12, Vnet_13, Vnet_14, Vnet_15);
	VHDL_Device_13: inverter port map (Vnet_2, S1);
	VHDL_Device_14: inverter port map (Vnet_3, S2);
	VHDL_Device_15: inverter port map (Vnet_4, S3);
	VHDL_Device_16: inverter port map (Vnet_8, S4);
	VHDL_Device_17: inverter port map (Vnet_9, S5);
	VHDL_Device_18: inverter port map (Vnet_11, S6);
	VHDL_Device_19: inverter port map (Vnet_15, S7);
	AN0 <= '0';
	AN3 <= '1';
	AN2 <= '1';
	AN1 <= '1';
end Structure;